accepted = [
    "Apache-2.0",
    "MIT",
    "ISC",
    "CDLA-Permissive-2.0",
    "Unicode-3.0",
    "Zlib",
    "GPL-3.0-or-later",
    "BSD-3-Clause",
    "MPL-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSL-1.0",
]
